import type { FingerpickPattern } from "@/lib/fingerpickTypes";

// Canonical decay-lab fixture. The pattern's display name is non-ASCII, so it is
// exported under this ASCII identifier. Pasted verbatim from the source JSON;
// do not edit the musical content to make it render — report instead.
export const DECAY_LAB_FIXTURE: FingerpickPattern = {
	id: "af8841ef-5b8e-4e5c-8ed0-cc6c089d23f9",
	name: "去北极忘记你",
	description: "",
	bpm: 60,
	timeSignature: [4, 4],
	measures: [
		{
			id: "e0646d6d-322e-41f6-8859-ad3756b8deef",
			slots: [
				{
					id: "c2c79ee5-f50c-48fc-ac73-85acbf52dabc",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "quarter",
				},
				{
					id: "27fb7426-627c-4053-9bb2-67dc5c5a5e38",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "quarter",
				},
				{
					id: "e28bc6eb-152d-4bc1-ba6c-a15c0f417285",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "eighth",
				},
				{
					id: "43312cf1-6bfc-4fcc-8207-7cc20de91fdb",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "eighth",
				},
				{
					id: "b76baca4-8672-4e51-8b52-334c63026823",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 1, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "quarter",
				},
			],
		},
		{
			id: "57e7f533-1a91-46d7-8a7d-83ab532d961c",
			slots: [
				{
					id: "61a971fe-858d-4bc4-9130-2c2a9d7166f0",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 1, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 3, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "9cb93a13-6a8a-45d8-8b05-f64dcb4c5b73",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "84012da1-245f-446b-967d-53288f59ed94",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "ffc8654b-c9fe-4378-82ec-5b7a08cb8a72",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "9c4f4fc8-d85e-4433-bab2-14378322828f",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: true, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "da190ab2-2ef8-4745-b305-e6cfa2b6d1c0",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "5f6746ba-4063-4da1-bf0c-6cc8167bc1d4",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 2, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "78c7c26c-2439-479d-bb33-ecdd987f5176",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 1, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "99e528ec-f11f-4842-8f37-eba2c6dad7a4",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 2, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "b612d2fa-2329-4d44-9b97-29ed39e252e4",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "e6aefd02-0020-44e2-b79e-7046e042dc78",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "776429bb-cd3c-4daf-aa69-63c1c33f0217",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "c32fcbd4-c983-4616-975a-26aafc543640",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 1, tied: false, muted: false, technique: null },
						{ fret: 2, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "f83b7e07-4fd0-4a9b-a8bc-ff206645665e",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "5c1dfa8c-ff0e-49fc-9945-00da3ea99ebd",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "9dfe8390-8913-4f94-a4a3-ffced597d969",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 4, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
			],
		},
		{
			id: "4d137b81-22ea-44db-aca1-2b0a6491b18c",
			slots: [
				{
					id: "b9046935-3ff1-4fac-b18c-bb1d01415eff",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 2, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "3911f6e6-a2dd-435a-8329-43315a6103ed",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "3020d687-45c5-4a34-ac66-725ed8556f72",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "fbba6ce5-5984-4c4a-bdec-2de5863d35e7",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "7ba7dbf5-8199-4e53-bb01-4d1148d9cb1a",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: true, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "23aee42b-00f4-487b-aff9-d474a801b76e",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "600a09c5-d341-48ba-a7c8-b8df86edd22a",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 4, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "36cfc8d5-0703-4c3a-ab30-b124dd66cf39",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "d57a07d3-d20b-4287-a711-f4c1e13eeff9",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "d6f0c280-b141-4aff-bb0c-87720d7c92ce",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "bd949451-b572-49f9-ab06-04fcbe6b99fa",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "6b26267f-2ce1-46f9-b656-7f48e11286c1",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 2, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "b92f64dc-45b6-4e4e-980b-655c8cc715c9",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 2, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "eighth",
				},
				{
					id: "a099997e-3e35-4bfd-a83e-85444d3511a0",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 3, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "eighth",
				},
			],
		},
		{
			id: "a5964960-58d0-4327-aa9a-93eb6efa86ce",
			slots: [
				{
					id: "c5f99563-ddcb-4076-b2d6-ce2fa9f65971",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 3, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "f6b1d09f-d5dc-41ab-bf36-abfda6b8505b",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "7b0a4af1-8250-4476-9045-24e442b6da64",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 1, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "734e165c-8b4a-4562-8155-de7cfc7e7b05",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 1, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "dde4ab7a-4f36-456e-8ebb-eb4dcefbe47b",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 1, tied: true, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "9bef888c-1bf7-43d3-bdc6-dd2092b96c55",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "dd5bb6b3-6b3f-4e8f-b75b-790c026cacd4",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "4895472c-d50c-431b-a4f5-43fdcea8d92a",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "f15b5d3c-37c0-48ff-a0c3-31ff24b7af97",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 2, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "ade28abb-46e7-4798-b18f-d8ea568cf1c3",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 2, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "9ef3ceb1-b2bf-4822-ba6e-3b47024a2b5a",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "f60c645b-0e20-40c3-b204-85a1832d4a6b",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 2, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "2bac7caf-85b1-4b5d-a989-2049e23bfbed",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 2, tied: true, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "4b379575-5f63-4cf8-a292-fef83c2662b8",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "d7e8d044-570b-47e9-a109-370aa41a60d6",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "2617d4c9-a61b-4d0c-981e-bda1568247e8",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
			],
		},
		{
			id: "ec3a5264-9ae0-4afe-9ca1-bf82d9e131da",
			slots: [
				{
					id: "bb63e955-f396-44a8-bcc1-017b47ab3f37",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 2, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 3, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "58887e62-f48e-4628-a312-1cd3ff2f644f",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "e42058b5-ff8b-444c-9f56-297e52ba679c",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "5204b7fe-ffea-481f-b0ca-727e7ee355d5",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "4a1542c6-c857-491b-94db-0eb4140fa4f8",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 0, tied: true, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "b2ab99f2-f7b1-4484-8b75-011be5d97782",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 3, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "dfd8f618-08b1-496d-8d95-44140a047402",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "184ea407-9c37-47d4-8986-1132e3c613a1",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 3, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "sixteenth",
				},
				{
					id: "71908a02-315e-4262-9118-11a50b6d1e6d",
					strings: [
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: 3, tied: true, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "quarter",
				},
				{
					id: "a2ce0a63-b1a2-47ce-87ad-fb9342e3bd00",
					strings: [
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: 1, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: 0, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
						{ fret: null, tied: false, muted: false, technique: null },
					],
					duration: "quarter",
				},
			],
		},
	],
};
